.\" SPDX-License-Identifier: Unlicense OR MIT
.\" Refer to the file 'LICENSE' in the nvxx distribution for license terms.
.Dd March 27, 2025
.Dt NVXX 3
.Os
.Sh NAME
.Nm nvxx
.Nd C++ interface for
.Xr nv 9
.Sh LIBRARY
.Lb libnvxx
.Sh SYNOPSIS
.In nvxx.h
.\" unfortunately, mdoc is not really set up for documenting C++ classes.
.Bd -literal
namespace bsd {

// exposition only
struct nv_fd {
        explicit nv_fd(int fd) noexcept;
        nv_fd(nv_fd &&other) noexcept;
        nv_fd(nv_fd const &) = delete;

        nv_fd& operator=(nv_fd &&other) noexcept;
        nv_fd& operator=(nv_fd const &) = delete;

        int get() const;
        int release() &&;
};

// exposition only
struct nv_error : std::runtime_error {
};

// exposition only
struct nv_error_state : nv_error {
	std::error_code error;
};

// exposition only
struct nv_key_not_found : nv_error {
	std::string key;
};

// exposition only
struct nv_key_exists : nv_error {
	std::string key;
};

// exposition only
template<typename T>
using container-type = ...;

// exposition only
struct const_nv_list : <unspecified> {
	const_nv_list();
	explicit const_nv_list(::nvlist_t const *);
	const_nv_list(const_nv_list const &);

	const_nv_list &operator=(const_nv_list const &);
	const_nv_list &operator=(nv_list const &);

	::nvlist_t const *ptr() const;

	void dump(int fd) const;
	void fdump(std::FILE *fp) const;

	std::size_t packed_size() const;
	std::vector<std::byte> pack() const;

	std::error_code error() const;

	explicit operator bool() const;

	bool empty() const;
	int flags() const;
	bool in_array() const;

	void send(int fd) const;

	bool exists(std::string_view key) const;
	bool exists_type(std::string_view key, int) const;
	bool exists_null(std::string_view key) const;
	bool exists_bool(std::string_view key) const;
	bool exists_number(std::string_view key) const;
	bool exists_string(std::string_view key) const;
	bool exists_binary(std::string_view key) const;
	bool exists_nvlist(std::string_view key) const;
	bool exists_descriptor(std::string_view key) const;

	auto get_bool(std::string_view key) const -> bool;
	auto get_number(std::string_view key) const -> std::uint64_t;
	auto get_string(std::string_view key) const -> std::string_view;
	auto get_descriptor(std::string_view key) const -> int;
	auto get_nvlist(std::string_view key) const -> const_nv_list;

	// exposition only
	auto get_binary(std::string_view key) const -> container-type<std::byte const>;

	bool exists_bool_array(std::string_view key) const;
	bool exists_number_array(std::string_view key) const;
	bool exists_string_array(std::string_view key) const;
	bool exists_descriptor_array(std::string_view key) const;
	bool exists_nvlist_array(std::string_view key) const;

	// exposition only
	auto get_bool_array(std::string_view key) const -> container-type<bool const>;
	auto get_number_array(std::string_view key) const -> container-type<std::uint64_t const>;
	auto get_string_array(std::string_view key) const -> container-type<std::string_view>;
	auto get_descriptor_array(std::string_view key) const -> container-type<int const>;
	auto get_nvlist_array(std::string_view key) const -> container-type<const_nv_list>;
};

// exposition only
struct nv_list : <unspecified> {
	explicit nv_list(int flags = 0);
	explicit nv_list(::nvlist_t *);
	nv_list(nv_list const &);
	nv_list(nv_list &&);

	nv_list &operator=(nv_list const &);
	nv_list &operator=(nv_list &&);

	::nvlist_t *ptr();
	::nvlist_t const *ptr() const;

	::nvlist_t *release() &&;

	void set_error(int error);

	void free(std::string_view name);

	operator const_nv_list() const;

	void add_null(std::string_view key);
	void add_bool(std::string_view key, bool value);
	void add_number(std::string_view key, std::uint64_t);
	void add_string(std::string_view key, std::string_view);
	void add_descriptor(std::string_view key, int);
	void add_nvlist(std::string_view key, const_nv_list const &);
	void add_binary(std::string_view key, std::span<std::byte const>);
	void add_binary_range(std::string_view key, std::ranges::range auto &&);

	void move_string(std::string_view key, char *);
	void move_descriptor(std::string_view key, int);
	void move_binary(std::string_view key, std::span<std::byte>);
	void move_nvlist(std::string_view key, nv_list &&);
	void move_nvlist(std::string_view key, ::nvlist_t *);

	void free(std::string_view key);
	void free_type(std::string_view key, int type);
	void free_null(std::string_view key);
	void free_bool(std::string_view key);
	void free_number(std::string_view key);
	void free_string(std::string_view key);
	void free_descriptor(std::string_view key);
	void free_binary(std::string_view key);
	void free_nvlist(std::string_view key);

	auto take_bool(std::string_view key) -> bool;
	auto take_number(std::string_view key) -> std::uint64_t;
	auto take_string(std::string_view key) -> std::string;
	auto take_descriptor(std::string_view key) -> nv_fd;
	auto take_nvlist(std::string_view key) -> nv_list;

	void move_bool_array(std::string_view key, std::span<bool>);
	void move_number_array(std::string_view key, std::span<std::uint64_t>);
	void move_string_array(std::string_view key, std::span<char *>);
	void move_descriptor_array(std::string_view key, std::span<int>);
	void move_nvlist_array(std::string_view key, std::span<::nvlist_t *>);

	void append_bool_array(std::string_view key, bool);
	void append_number_array(std::string_view key, std::uint64_t);
	void append_string_array(std::string_view key, std::string_view);
	void append_descriptor_array(std::string_view key, int);
	void append_nvlist_array(std::string_view key, const_nv_list const &);

	void free_bool_array(std::string_view key);
	void free_number_array(std::string_view key);
	void free_string_array(std::string_view key);
	void free_nvlist_array(std::string_view key);
	void free_descriptor_array(std::string_view key);

	void add_bool_array(std::string_view key, std::span<bool const>);
	void add_number_array(std::string_view key, std::span<std::uint64_t const>);
	void add_string_array(std::string_view key, std::span<std::string_view const>);
	void add_descriptor_array(std::string_view key, std::span<int const>);
	void add_nvlist_array(std::string_view key, std::span<const_nv_list const>);
	void add_nvlist_array(std::string_view key, std::span<nv_list const>);

	void add_bool_range(std::string_view key, std::ranges::range auto &&);
	void add_number_range(std::string_view key, std::ranges::range auto &&);
	void add_string_range(std::string_view key, std::ranges::range auto &&);
	void add_descriptor_range(std::string_view key, std::ranges::range auto &&);
	void add_nvlist_range(std::string_view key, std::ranges::range auto &&);

	// exposition only
	auto take_bool_array(std::string_view key) -> container-type<bool>;
	auto take_number_array(std::string_view key) -> container-type<std::uint64_t>;
	auto take_string_array(std::string_view key) -> container-type<std::string>;
	auto take_nvlist_array(std::string_view key) -> container-type<nv_list>;
	auto take_descriptor_array(std::string_view __key) -> container-type<nv_fd>;
	auto take_binary(std::string_view key) -> container-type<std::byte>;
};

// range support

using nv_list_key_t = std::string_view;

using nv_list_value_t = std::variant<
	nullptr_t,			/* null */
	bool,				/* bool */
	std::uint64_t,			/* number */
	std::string_view,		/* string */
	const_nv_list,			/* nvlist */
	int,				/* descriptor */
	std::span<std::byte const>,	/* binary */
	std::span<bool const>,		/* bool array */
	std::span<std::uint64_t const>,	/* number array */
	std::vector<std::string_view>,	/* string array */
	std::span<int const>,		/* descriptor array */
	std::vector<const_nv_list>	/* nvlist array */
>;

using nv_list_pair_t = std::pair<nv_list_key_t, nv_list_value_t>;

struct nv_list_iterator;

nv_list_iterator begin(const_nv_list const &);
nv_list_iterator begin(nv_list const &);

// exposition only
unspecified-type end(const_nv_list const &);
unspecified-type end(nv_list const &);

// serialization interface

template<typename T>
struct nv_schema;

// exposition only
struct nv_literal {
	nv_literal(std::string key, std::string value);
};

template<typename Object, typename Member>
struct nv_field {
	nv_object(std::string key, Member Object::* ptr);
};

// exposition only
template<typename Object, typename Member>
struct nv_object {
	nv_object(std::string key, Member Object::* ptr);
};

nv_list nv_serialize(auto &&object);
nv_list nv_serialize(auto &&object, auto const &schema);

void nv_deserialize(const_nv_list const &, auto &&object);
void nv_deserialize(const_nv_list const &, auto &&object, auto const &schema);

} // namespace bsd
.Ed
.Sh DESCRIPTION
The
.Nm
library provides a C++ wrapper around the
.Xr nv 9
C library.
The library is ABI compatible with the C library, in the sense that it can both
consume and produce pointers of type
.Vt nvlist_t .
.Sh TYPES
The library provides two basic types:
.Vt nv_list ,
which represents an owning, mutable
.Vt nvlist_t * ,
and
.Vt const_nv_list ,
which represents a non-owning, immutable
.Vt const nvlist_t * .
.Pp
A
.Vt const_nv_list
provides all non-mutating operations on the nvlist, such as testing for the
existence of a key, fetching a key, and packing or sending an nvlist.
A
.Vt const_nv_list
can be constructed from an existing
.Vt const nvlist_t * ,
or from an
.Vt nv_list ,
or copy-constructed from another
.Vt const_nv_list .
Because
.Vt const_nv_list
is non-owning, it always refers to an existing nvlist and will never destroy
the object to which it refers; this is the responsibility of the user.
.Pp
An
.Vt nv_list
provides all the operations that
.Vt const_nv_list
provides, plus additional mutating operations such as adding or removing keys.
An
.Vt nv_list
can be constructed from an existing
.Vt nvlist_t * ,
in which case it will take ownership of the nvlist.
It may also be copy-constructed from another
.Vt nv_list
or
.Vt const_nv_list ,
in which case it will duplicate the underlying list using
.Xr nvlist_clone 3 ,
and it may be default-constructed, in which case it will create a new nvlist
using
.Xr nvlist_create 3 .
To pass flags to
.Xr nvlist_create 3 ,
use the optional
.Fa "int flags"
argument to the constructor.
.Pp
Both
.Vt const_nv list
and
.Vt nv_list
support copy-initialization and exception-free move-initialization.
In addition,
.Vt nv_list
supports default-initialization.
.Sh ERROR HANDLING
The library defines a base error class called
.Vt nv_error ,
which is thrown when an error is detected.
Several more specific derived exception types are defined:
.Bl -tag -width indent
.It Vt nv_error_state
Thrown when attempting to perform an operation on an nvlist which is in the
error state, such as adding or removing a key.
This is also thrown when attempting to construct an
.Vt nv_list
or
.Vt const_nv_list
using an
.Vt nvlist_t *
which is in the error state.
.It Vt nv_key_not_found
Thrown when an attempt is made to fetch a key which does not exist in the
nvlist.
.It Vt nv_key_exists
Thrown when an attempt is made to add a key to an nvlist when a key of the same
name is already present, and the list does permit duplicates.
.El
.Pp
The underlying C library has the concept of an error state, an internal flag
on the nvlist which indicates an error has previously occurred.
Once an nvlist is in the error state, no operations on the nvlist are
permitted.
This error state cannot be cleared.
.Pp
The C++ library will prohibit any operation which would result in the error
state being set on the underlying nvlist, and such operations will throw an
exception instead.
If the underlying nvlist does enter the error state (for example, because the
nvlist was manually modified using the
.Fn ptr
member function), then all subsequent operations will fail and throw the
.Vt nv_error_state
exception.
The
.Va nv_error_state::error
member variable may then be used to determine which specific error occurred.
.Sh THE NV_FD TYPE
The C++ library uses a type called
.Vt bsd::nv_fd
for functions which take or return file descriptors.
An
.Vt nv_fd
may be created from a file descriptor, at which point it takes ownership of the
file descriptor and will close it when destructed.
An
.Vt nv_fd
may be move-initialized and move-assigned, but may not be copied.
.Pp
To retrieve the file descriptor stored by an
.Vt nv_fd
without taking ownership, use the
.Fn get
member function.
To retrieve the file descriptor and take ownership of it, use the
.Fn release
member function, which leaves the
.Vt nv_fd
in a moved-from state.
.Pp
A moved-from
.Vt nv_fd
may be assigned to, but any attempt to retrieve the store file descriptor will
throw an exception of type
.Vt std::logic_error .
.Sh CONST_NV_LIST OPERATIONS
The
.Fn dump
and
.Fn fdump
member functions write the contents of the nvlist to the provided file
descriptor or file pointer in a human-readable format.
These functions are intended for debugging; the output format should not be
considered stable.
.Pp
The
.Fn error
member function returns the current error code of the nvlist.
If the nvlist is not in an error state, a default-initialized
.Fn std::error_code
is returned.
.Pp
The
.Fn "operator bool"
member function returns
.Dv false
if the nvlist is in an error state, otherwise
.Dv true .
.Pp
The
.Fn empty
member function returns
.Dv true
if the nvlist is empty, i.e. it contains no values.
.Pp
The
.Fn flags
member function returns the flags that were used to create this nvlist.
Refer to
.Xr nvlist_create 9
for documentation on the flags that may be set here.
.Pp
.Fn
The
.Fn pack
member function serializes the nvlist to a byte stream and returns it.
The byte stream can later be passed to
.Fn nv_list::unpack
to turn it back into an nvlist.
If the pack operation fails (for example, due to an out-of-memory condition),
then an exception of type
.Vt std::system_error
will be thrown.
.Pp
The
.Fn packed_size
member function returns the number of bytes that would be generated by
.Fn pack .
.Pp
The
.Fn send
function packs the contents of the nvlist as if by
.Fn pack ,
and sends the resulting byte stream over the given file descriptor.
If the nvlist is in the error state, an exception of type
.Vt nv_error_state
is thrown.
If an operating system error occurs while writing to the file descriptor,
an exception of type
.Vt std::system_error
is thrown.
.Pp
The
.Fn exists
member function returns
.Dv true
if a key by the given name exists, otherwise
.Dv false .
.Pp
The
.Fn exists_type
member function returns
.Dv true
if a key by the given name exists with the specified type, which should be one
of the type constants defined in <sys/nv.h>.
.Pp
The
.Fn exists_null ,
.Fn exists_bool ,
.Fn exists_number ,
.Fn exists_string ,
.Fn exists_nvlist ,
.Fn exists_binary ,
.Fn exists_bool_array ,
.Fn exists_number_array ,
.Fn exists_string_array ,
.Fn exists_nvlist_array
and
.Fn exists_descriptor_array
member functions return
.Dv true
if a key with the given name exists in the nvlist, or otherwise
.Dv false .
These functions may be called on an nvlist which is in the error state.
.Pp
The
.Fn get_bool ,
.Fn get_number ,
.Fn get_string ,
.Fn get_nvlist ,
.Fn get_descriptor ,
.Fn get_binary ,
.Fn get_bool_array ,
.Fn get_number_array ,
.Fn get_string_array ,
.Fn get_nvlist_array
and
.Fn get_descriptor_array
member functions return the value of the key by the given name in the nvlist.
If a key by that name does not exist, then an exception of type
.Vt nv_key_not_found
is thrown.
For the array variants, the return type
.Vt container-type<T>
is defined to be an unspecified container type
.Vt C
which fulfills the requirements of
.Vt std::ranges::continguous_range
and where
.Vt std::ranges::range_value_t<C>
is equal to
.Vt T .
.Sh NV_LIST OPERATIONS
The
.Fn add_null ,
.Fn add_bool ,
.Fn add_number ,
.Fn add_string  and
.Fn add_nvlist
and
.Fn add_binary
member functions add a new key to the nvlist of the appropriate type with the
given name.
If a value of the given name is already present in the nvlist, and the nvlist
does not permit duplicate value names, then an exception of type
.Vt nv_key_exists
is thrown, and the nvlist is placed in the error state.
If the nvlist is in an error state, then an exception of type
.Vt nv_error_state
is thrown, and the key is not added.
.Pp
The
.Fn add_descriptor
member function adds a new file descriptor to the nvlist with the given name.
The file descriptor will be duplicated using
.Xr dup 2
prior to being added, and if later removed, will be closed using
.Xr close 2 .
The behaviour when attempting to add a duplicate value name is the same as
described for the other
.Fn add_
member functions.
.Pp
The
.Fn add_bool_array ,
.Fn add_number_array ,
.Fn add_string_array ,
.Fn add_nvlist_array
and
.Fn add_descriptor_array
functions add an array of that type to the nvlist.
The array should be provided as an
.Vt std::span<>
of the appropriate type; the value type of the span may be
.Vt const .
The behaviour when attempting to add a duplicate value name is the same as
described for the
.Fn add_
member functions.
.Pp
The
.Fn add_bool_range ,
.Fn add_number_range ,
.Fn add_string_range ,
.Fn add_nvlist_range
and
.Fn add_descriptor_range
functions add an array of that type to the nvlist, where the contents of the
array are provided as a type which fulfills the requirements of
.Vt std::ranges::range .
The value type of the range may be
.Vt const .
The behaviour when attempting to add a duplicate value name is the same as
described for the
.Fn add_
member functions.
.Pp
The
.Fn free
member function removes the first key of the given name.
If no such key exists, an exception of type
.Vt nv_key_not_found
is thrown.
.Pp
The
.Fn free_type
member function removes the first key of the given name and type.
The
.Fa type
arguments should be one of the type constants defined in <sys/nv.h>.
If no such key exists, an exception of type
.Vt nv_key_not_found
is thrown.
.Pp
The
.Fn free_null ,
.Fn free_bool ,
.Fn free_number ,
.Fn free_string ,
.Fn free_nvlist ,
.Fn free_descriptor ,
.Fn free_binary ,
.Fn free_bool_array ,
.Fn free_number_array ,
.Fn free_string_array ,
.Fn free_nvlist_array
and
.Fn free_descriptor_array
member functions remove the first value of the given name of the appropriate
type from the nvlist.
If no suitable value is found to remove, an exception of type
.Vt nv_key_not_found
is thrown.
.Pp
The
.Fn take_null ,
.Fn take_bool ,
.Fn take_number ,
.Fn take_string ,
.Fn take_nvlist ,
.Fn take_descriptor ,
.Fn take_binary ,
.Fn take_bool_array ,
.Fn take_number_array ,
.Fn take_string_array ,
.Fn take_nvlist_array
and
.Fn take_descriptor_array
member functions remove the first value of the given name of the appropriate
type from the nvlist, and return the value which was removed.
If no suitable value is found to remove, an exception of type
.Vt nv_key_not_found
is thrown.
.Pp
The
.Fn move_string
member function takes ownership of the provided string pointer, which must be a
NUL-terminated C string allocated using
.Fn std::malloc ,
and adds it to the nvlist.
The string will later be freed using
.Fn std::free .
The behaviour when attempting to add a duplicate value name is the same as
described for the
.Fn add_
member functions.
.Pp
The
.Fn move_nvlist
member function takes ownership of the provided nvlist and adds it to the
nvlist.
The behaviour when attempting to add a duplicate value name is the same as
described for the
.Fn add_
member functions.
.Pp
The
.Fn move_descriptor
member function takes ownership of the provided file descriptor and adds it to
the nvlist.
This equivalent to calling
.Fn add_descriptor ,
except that the file descriptor is not duplicated.
.Pp
The
.Fn move_bool_array ,
.Fn move_number_array ,
.Fn move_string_array ,
.Fn move_nvlist_array
and
.Fn move_descriptor_array
member functions take ownership of the provided C array of the given type
and add it to the nvlist as an array.
The array must be a C array which was previously allocated using
.Fn std::malloc .
In the case of
.Fn move_string_array
and
.Fn move_nvlist_array ,
the nvlist takes ownership of the member values and will later free them using
.Fn std::free
(for strings) or
.Xr nvlist_destroy 3
(for nvlists).
In the case of
.Fn move_descriptor_array ,
the nvlist takes ownership of the member descriptors and will later close them
using
.Xr close 2 .
.Sh RANGE SUPPORT
Both
.Vt nv_list
and
.Vt const_nv_list
are ranges fulfilling the requirements of
.Vt std::ranges::forward_range .
The list may be iterated to enumerate values of type
.Vt nv_list_pair_t ,
which contains the name and value of each nv_list element.
.Pp
Modifying an
.Vt nv_list
invalidates any iterators for that list and any instances of
.Vt const_nv_list
which refer to that list.
.Sh SERIALIZATION INTERFACE
The serialization interface provides a simple interface to the nvlist library
which allows conversion between nvlists and C++ objects.
To use the serialization interface, the object to be serialized must have a
schema, which is typically provided by specializing
.Vt nv_schema
for the object type.
The specialization should have a single member function called
.Fn get
which returns the schema.
.Pp
The schema is defined using one or more schema elements, which are joined using
the >> operator.
The available field types are:
.Bl -tag -width indent
.It Fn nv_literal name value
A literal value.
When serializing the object, the literal value will be added to the nvlist.
When deserializing the object, deserialization will fail if the literal value
is not present in the nvlist.
.It Fn nv_field name mptr
An object member variable containing a basic type,
identified by its name and a pointer-to-member.
The following types are supported:
.Pp
.Bl -hyphen -compact
.It
.Vt bool
.It
.Vt std::uint64_t
.It
.Vt std::string
.It
.Vt std::string_view
.It
.Vt nv_list
.It
.Vt const_nv_list
.It
.Vt std::optional<T>
for any type
.Vt T
listed above
.It
a container type of any type listed above, as long as the container supports
.Vt std::from_range
construction.
.El
.It Fn nv_object name mptr
An object member variable whose type has its own schema defined.
This allows nested objects to be serialized.
.El
.Pp
For example, a simple schema could be defined like this:
.Bd -literal
struct object {
	std::uint64_t i;
	std::string s;
};

template<> struct bsd::nv_schema<object> {
	auto get() {
		return bsd::nv_field("int field", &object::i)
		    >> bsd::nv_field("string field", &object::s);
	}
};
.Ed
.Pp
As an alternative to specializing
.Vt nv_schema ,
a schema may also be passed directly to
.Fn nv_serialize
and
.Fn nv_deserialize .
